- name: Create Directory
  file:
    path: "{{ kafka_home }}/kafka"
    state: directory
    owner: kafka
    group: kafka
    mode: 0775

- name: Download and Extract Kafka
  unarchive:
    src: "{{ kafka_url }}"
    dest: "{{ kafka_home }}/kafka"
    remote_src: yes
    extra_opts: [--strip-components=1]
  become: yes
  become_user: kafka

- name: Update kafka's server.properties config file
  lineinfile:
    dest: "{{ kafka_home }}/kafka/config/server.properties"
    state: present
    regexp: '^delete.topic.enable'
    line: 'delete.topic.enable = true'
  become: yes
  become_user: kafka
