- name: Set Timezone
  timezone: >
    name={{ timezone }}
- name: Upgrade
  apt: update_cache=yes upgrade=yes cache_valid_time=86400
- name: Install Java
  apt:
    pkg:
      - openjdk-11-jre-headless
    state: present
    update_cache: yes
- name: Set JAVA_HOME
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: '^JAVA_HOME'
    line: 'JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64'
